import React,{useEffect,useMemo,useState} from "react";import{createRoot}from"react-dom/client";import{motion}from"framer-motion";import{Bot,CalendarDays,Home,Info,Languages,Pause,Play,Repeat2,Send,Settings,X}from"lucide-react";import"./styles.css";

const D=[
{day:"Sunday",hi:"रविवार",e:"🌅",focus:"Surya · health, vision & success",m:[["Surya Mantra","ॐ घृणि सूर्याय नमः","Om Ghrini Suryaya Namaha","A devotional salutation to Surya, the Sun."],["Surya Gayatri Mantra","ॐ भास्कराय विद्महे महातेजाय धीमहि तन्नो सूर्यः प्रचोदयात","Om Bhaskaraya Vidmahe Mahatejaya Dhimahi Tanno Suryah Prachodayat","A prayer for clarity, inner light and wise direction."]]},
{day:"Monday",hi:"सोमवार",e:"🌙",focus:"Shiva · peace & letting go",m:[["Shiva Mantra","ॐ नमः शिवाय","Om Namah Shivaya","A salutation to Lord Shiva expressing reverence and surrender."],["Maha Mrityunjaya Mantra","ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥","Om Tryambakam Yajamahe Sugandhim Pushti-Vardhanam","A traditional prayer for freedom from fear and suffering."]]},
{day:"Tuesday",hi:"मंगलवार",e:"☄️",focus:"Hanuman & Ganesha · courage & obstacles",m:[["Hanuman Mantra","ॐ हनुमते नमः","Om Hanumate Namaha","A salutation to Hanuman, associated with strength, courage and devotion."],["Ganesha Mantra","ॐ गं गणपतये नमः","Om Gam Ganapataye Namaha","A traditional invocation to Ganesha at the beginning of undertakings."]]},
{day:"Wednesday",hi:"बुधवार",e:"🔱",focus:"Krishna & Vishnu · wisdom & devotion",m:[["Hare Krishna","हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे॥","Hare Krishna Hare Krishna Krishna Krishna Hare Hare","A devotional chant of remembrance using the names of Krishna and Rama."],["Vishnu Mantra","ॐ नमो भगवते वासुदेवाय","Om Namo Bhagavate Vasudevaya","A traditional salutation to Lord Vishnu."]]},
{day:"Thursday",hi:"गुरुवार",e:"🌾",focus:"Vishnu & Guru · learning & growth",m:[["Vishnu Dhyaan Mantra","ॐ नमो नारायणाय","Om Namo Narayanaya","A devotional salutation to Narayana."],["Guru Mantra","ॐ गुरवे नमः","Om Gurave Namaha","A salutation to the Guru, expressing respect for wisdom and guidance."]]},
{day:"Friday",hi:"शुक्रवार",e:"🌸",focus:"Lakshmi & Durga · abundance & grace",m:[["Lakshmi Mantra","ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै अस्माकम् दारिद्र्य नाशय प्रचुर धन देहि देहि क्लीं ह्रीं श्रीं ॐ","Om Shreem Hreem Kleem Tribhuvan Maha-Lakshmyai","A traditional prayer to Mahalakshmi seeking prosperity and abundance."],["Mahalakshmi Mantra","ॐ श्री महालक्ष्म्यै नमः","Om Shri Maha Lakshmyai Namaha","A simple salutation to Mahalakshmi."]]},
{day:"Saturday",hi:"शनिवार",e:"⚖️",focus:"Shani & Hanuman · discipline & steadiness",m:[["Shani Mantra","ॐ शं शनैश्चराय नमः","Om Sham Shanaishcharaya Namaha","A traditional salutation to Shani, associated with discipline and patience."],["Shani Maha Mantra","ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः","Om Praam Preem Proum Sah Shanaishcharaya Namaha","A longer devotional mantra dedicated to Shani."]]}
];

function App(){const today=new Date().getDay();const[t,setT]=useState(today);const[mi,setMi]=useState(0);const[tab,setTab]=useState("home");const[play,setPlay]=useState(false);const[repeat,setRepeat]=useState(11);const[q,setQ]=useState("");const[msg,setMsg]=useState([]);const[d,setD]=useState("English");const day=D[t],mantra=day.m[mi];useEffect(()=>{"serviceWorker"in navigator&&navigator.serviceWorker.register("/sw.js")},[]);useEffect(()=>setMi(0),[t]);const toggleAudio=()=>{if(!("speechSynthesis"in window))return;if(play){window.speechSynthesis.cancel();setPlay(false);return}const u=new SpeechSynthesisUtterance(mantra[1]);u.lang="hi-IN";u.rate=.72;u.pitch=.95;u.onend=()=>setPlay(false);window.speechSynthesis.cancel();window.speechSynthesis.speak(u);setPlay(true)};const ask=x=>{if(!x.trim())return;setMsg([...msg,{r:"u",x},{r:"a",x:"Connect your preferred AI API here for live online answers. Local meaning: "+mantra[3]}]);setQ("")};return <div className="app"><header><div><div className="brand"><img src="/logo.svg" alt="MantraMitra logo"/><b>MantraMitra</b></div><small>Daily mantras · peaceful listening</small></div><button onClick={()=>setD(d==="English"?"हिन्दी":d==="हिन्दी"?"বাংলা":"English")}><Languages size={19}/></button></header><main>
{tab==="home"&&<><section className="hero"><div><small>TODAY</small><h1>{day.e} {day.day} <em>{day.hi}</em></h1><p>{day.focus}</p></div><span>OFFLINE READY</span></section><section className={"player "+(play?"on":"")}><div className="orbarea"><div className="orb">ॐ</div>{[1,2,3].map(x=><motion.i key={x} animate={{scale:play?[1,1.25+x*.07,1]:1,opacity:play?[.2,.45,.08]:.08}} transition={{duration:2.1+x*.3,repeat:Infinity}}/>)}</div><div className="pill">{day.e} {day.day}</div><h2>{mantra[0]}</h2><div className="sanskrit">{mantra[1]}</div><div className="translit">{mantra[2]}</div><div className="controls"><button className="play" onClick={toggleAudio}>{play?<Pause/>:<Play fill="currentColor"/>}{play?"Pause":"Play"}</button><button className="secondary" onClick={()=>setRepeat(repeat===11?108:11)}><Repeat2 size={18}/>{repeat}×</button></div><div className="bars">{Array.from({length:20}).map((_,i)=><motion.span key={i} animate={{height:play?[8,10+(i%7)*5,8]:8}} transition={{repeat:Infinity,duration:.6+i*.02}}/>)}</div><div className="meaning"><b><Info size={15}/> Simple meaning</b><p>{mantra[3]}</p><button onClick={()=>setTab("ask")}>💬 Ask about this mantra</button></div></section><h3 className="sect">Today's mantras <button onClick={()=>setTab("week")}>View week</button></h3>{day.m.map((m,i)=><button className={"row "+(mi===i?"sel":"")} key={m[0]} onClick={()=>{setMi(i);setPlay(false)}}><strong>{String(i+1).padStart(2,"0")}</strong><div><b>{m[0]}</b><small>{m[2]}</small></div><Play size={17}/></button>)}</>}
{tab==="week"&&<><div className="section"><small>WEEKLY RHYTHM</small><h2>Choose a day</h2><p>All mantra text and playback content can be bundled locally.</p></div><div className="days">{D.map((x,i)=><button className={i===t?"sel":""} onClick={()=>{setT(i);setTab("home")}} key={x.day}><span>{x.e}</span><b>{x.day}</b><small>{x.hi}</small><em>{x.m.length} mantras</em></button>)}</div></>}
{tab==="ask"&&<><div className="section"><small>ONLINE GUIDE</small><h2>Ask about a mantra</h2><p>The chatbot is online-only; mantra listening remains offline-capable.</p></div><div className="suggests">{["What is the meaning?","Why chant this mantra?","How can I chant it?"].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div><div className="chat">{msg.length?msg.map((x,i)=><div key={i} className={"bubble "+x.r}>{x.x}</div>):<div className="empty"><Bot size={36}/><p>Ask a simple question about <b>{mantra[0]}</b>.</p></div>}</div><div className="input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask(q)} placeholder="Ask in English, Hindi or Bengali…"/><button onClick={()=>ask(q)}><Send size={18}/></button></div></>}
{tab==="more"&&<><div className="section"><small>MORE</small><h2>Made for family use</h2><p>Large controls, local-first playback, and a calm interface.</p></div><div className="info"><strong>🔊 Offline audio</strong><p>Place your recordings under public/audio and point the player to them.</p></div><div className="info"><strong>🤖 Online AI</strong><p>Connect any API endpoint later; the core player never depends on it.</p></div><div className="info"><strong>📱 Installable</strong><p>Use your browser's “Add to Home Screen” option to make it feel like an app.</p></div></>}
</main><nav><button className={tab==="home"?"on":""} onClick={()=>setTab("home")}><Home size={20}/>Home</button><button className={tab==="week"?"on":""} onClick={()=>setTab("week")}><CalendarDays size={20}/>Week</button><button className={tab==="ask"?"on":""} onClick={()=>setTab("ask")}><Bot size={20}/>Ask</button><button className={tab==="more"?"on":""} onClick={()=>setTab("more")}><Settings size={20}/>More</button></nav></div>}

createRoot(document.getElementById("root")).render(<App/>);