import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import{motion}from"framer-motion";import{Bot,CalendarDays,Home,Info,Languages,Pause,Play,Send,Settings}from"lucide-react";import"./styles.css";

const D=[
{day:"Sunday",hi:"रविवार",e:"🌅",focus:"Surya · health, vision & success",m:[["Surya Mantra","ॐ घृणि सूर्याय नमः","Om Ghrini Suryaya Namaha","A devotional salutation to Surya, the Sun.",null,"/audio/108x/surya-mantra.mp3"],["Surya Gayatri Mantra","ॐ भास्कराय विद्महे महातेजाय धीमहि तन्नो सूर्यः प्रचोदयात","Om Bhaskaraya Vidmahe Mahatejaya Dhimahi Tanno Suryah Prachodayat","A prayer for clarity, inner light and wise direction.",null,"/audio/108x/surya-gayatri.mp3"]]},
{day:"Monday",hi:"सोमवार",e:"🌙",focus:"Shiva · peace & letting go",m:[["Shiva Mantra","ॐ नमः शिवाय","Om Namah Shivaya","A salutation to Lord Shiva expressing reverence and surrender.",null,"/audio/108x/shiva-mantra.mp3"],["Maha Mrityunjaya Mantra","ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥","Om Tryambakam Yajamahe Sugandhim Pushti-Vardhanam","A traditional prayer for freedom from fear and suffering.",null,"/audio/108x/maha-mrityunjaya.mp3"]]},
{day:"Tuesday",hi:"मंगलवार",e:"☄️",focus:"Hanuman & Ganesha · courage & obstacles",m:[["Hanuman Mantra","ॐ हनुमते नमः","Om Hanumate Namaha","A salutation to Hanuman, associated with strength, courage and devotion.",null,"/audio/108x/hanuman-mantra.mp3"],["Ganesha Mantra","ॐ गं गणपतये नमः","Om Gam Ganapataye Namaha","A traditional invocation to Ganesha at the beginning of undertakings.",null,"/audio/108x/ganesha.mp3"]]},
{day:"Wednesday",hi:"बुधवार",e:"🔱",focus:"Krishna & Vishnu · wisdom & devotion",m:[["Hare Krishna","हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे॥","Hare Krishna Hare Krishna Krishna Krishna Hare Hare","A devotional chant of remembrance using the names of Krishna and Rama.",null,"/audio/108x/hare-krishna.mp3"],["Vishnu Mantra","ॐ नमो भगवते वासुदेवाय","Om Namo Bhagavate Vasudevaya","A traditional salutation to Lord Vishnu.",null,"/audio/108x/vishnu-mantra.mp3"]]},
{day:"Thursday",hi:"गुरुवार",e:"🌾",focus:"Vishnu & Guru · learning & growth",m:[["Vishnu Dhyaan Mantra","ॐ नमो नारायणाय","Om Namo Narayanaya","A devotional salutation to Narayana.",null,"/audio/108x/vishnu-dhyaan.mp3"],["Guru Mantra","ॐ गुरवे नमः","Om Gurave Namaha","A salutation to the Guru, expressing respect for wisdom and guidance.",null,"/audio/108x/guru-mantra.mp3"]]},
{day:"Friday",hi:"शुक्रवार",e:"🌸",focus:"Lakshmi & Durga · abundance & grace",m:[["Lakshmi Mantra","ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै अस्माकम् दारिद्र्य नाशय प्रचुर धन देहि देहि क्लीं ह्रीं श्रीं ॐ","Om Shreem Hreem Kleem Tribhuvan Maha-Lakshmyai","A traditional prayer to Mahalakshmi seeking prosperity and abundance.",null,"/audio/108x/lakshmi-mantra.mp3"],["Mahalakshmi Mantra","ॐ श्री महालक्ष्म्यै नमः","Om Shri Maha Lakshmyai Namaha","A simple salutation to Mahalakshmi.",null,"/audio/108x/mahalakshmi.mp3"]]},
{day:"Saturday",hi:"शनिवार",e:"⚖️",focus:"Shani & Hanuman · discipline & steadiness",m:[["Shani Mantra","ॐ शं शनैश्चराय नमः","Om Sham Shanaishcharaya Namaha","A traditional salutation to Shani, associated with discipline and patience.",null,"/audio/108x/shani.mp3"],["Shani Maha Mantra","ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः","Om Praam Preem Proum Sah Shanaishcharaya Namaha","A longer devotional mantra dedicated to Shani.",null,"/audio/108x/shani-maha-mantra.mp3"]]}
];

function App(){const today=new Date().getDay();const[t,setT]=useState(today);const[mi,setMi]=useState(0);const[tab,setTab]=useState("home");const[play,setPlay]=useState(false);const[q,setQ]=useState("");const[msg,setMsg]=useState([]);const[loading,setLoading]=useState(false);const[d,setD]=useState("English");const audioRef=useRef(null);const day=D[t],mantra=day.m[mi];
useEffect(()=>{"serviceWorker"in navigator&&navigator.serviceWorker.register("/sw.js")},[]);
useEffect(()=>{setMi(0)},[t]);
useEffect(()=>{const a=audioRef.current;if(a){a.pause();a.currentTime=0}setPlay(false)},[t,mi]);
const stopAudio=()=>{const a=audioRef.current;if(a){a.pause();a.currentTime=0}setPlay(false)};
const toggleAudio=async()=>{const a=audioRef.current;if(!a)return;if(play){a.pause();setPlay(false);return}try{await a.play();setPlay(true)}catch{setPlay(false)}};
const handleEnded=()=>setPlay(false);
const ask=async x=>{const question=x.trim();if(!question||loading)return;const userMessage={r:"u",x:question};setMsg(v=>[...v,userMessage]);setQ("");setLoading(true);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,mantra:{name:mantra[0],sanskrit:mantra[1],transliteration:mantra[2],meaning:mantra[3]}})});const data=await res.json();if(!res.ok)throw new Error(data.error||"The AI guide could not respond.");setMsg(v=>[...v,{r:"a",x:data.answer}])}catch(e){setMsg(v=>[...v,{r:"a",x:"I couldn’t reach the online AI guide right now. Here is the simple meaning: "+mantra[3]}])}finally{setLoading(false)}};
return <div className="app"><header><div><div className="brand"><img src="/logo.svg" alt="MantraMitra logo"/><b>MantraMitra</b></div><small>Daily mantras · peaceful listening</small></div><button onClick={()=>setD(d==="English"?"हिन्दी":d==="हिन्दी"?"বাংলা":"English")}><Languages size={19}/></button></header><main>
{tab==="home"&&<><section className="hero"><div><small>TODAY</small><h1>{day.e} {day.day} <em>{day.hi}</em></h1><p>{day.focus}</p></div><span>OFFLINE READY</span></section><section className={"player "+(play?"on":"")}><audio ref={audioRef} src={mantra[5]} preload="metadata" onEnded={handleEnded} aria-hidden="true"/><div className="orbarea"><div className="orb">ॐ</div>{[1,2,3].map(x=><motion.i key={x} animate={{scale:play?[1,1.25+x*.07,1]:1,opacity:play?[.2,.45,.08]:.08}} transition={{duration:2.1+x*.3,repeat:Infinity}}/>)}</div><div className="pill">{day.e} {day.day}</div><h2>{mantra[0]}</h2><div className="sanskrit">{mantra[1]}</div><div className="translit">{mantra[2]}</div><div className="audio-note">🎙️ Full-length 108× Sanskrit recording · offline ready</div><div className="controls"><button className="play" onClick={toggleAudio}>{play?<Pause/>:<Play fill="currentColor"/>}{play?"Pause":"Play"}</button></div><div className="progress-count">108× full recording</div><div className="bars">{Array.from({length:20}).map((_,i)=><motion.span key={i} animate={{height:play?[8,10+(i%7)*5,8]:8}} transition={{repeat:Infinity,duration:.6+i*.02}}/>)}</div><div className="meaning"><b><Info size={15}/> Simple meaning</b><p>{mantra[3]}</p><button onClick={()=>setTab("ask")}>💬 Ask about this mantra</button></div></section><h3 className="sect">Today's mantras <button onClick={()=>setTab("week")}>View week</button></h3>{day.m.map((m,i)=><button className={"row "+(mi===i?"sel":"")} key={m[0]} onClick={()=>{stopAudio();setMi(i)}}><strong>{String(i+1).padStart(2,"0")}</strong><div><b>{m[0]}</b><small>{m[2]}</small></div><Play size={17}/></button>)}</>}
{tab==="week"&&<><div className="section"><small>WEEKLY RHYTHM</small><h2>Choose a day</h2><p>All 108× recordings are bundled as full-length files for offline playback. The 11× collection will be added separately.</p></div><div className="days">{D.map((x,i)=><button className={i===t?"sel":""} onClick={()=>{setT(i);setTab("home")}} key={x.day}><span>{x.e}</span><b>{x.day}</b><small>{x.hi}</small><em>{x.m.length} mantras</em></button>)}</div></>}
{tab==="ask"&&<><div className="section"><small>ONLINE GUIDE</small><h2>Ask about a mantra</h2><p>The chatbot is online-only and powered by DeepSeek V4.1 Flash through NVIDIA AI; mantra listening remains offline-capable.</p></div><div className="suggests">{["What is the meaning?","Why chant this mantra?","How can I chant it?"].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div><div className="chat">{msg.length?msg.map((x,i)=><div key={i} className={"bubble "+x.r}>{x.x}</div>):<div className="empty"><Bot size={36}/><p>Ask a simple question about <b>{mantra[0]}</b>.</p></div>}{loading&&<div className="bubble a">Thinking about this mantra…</div>}</div><div className="input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask(q)} placeholder="Ask in English, Hindi or Bengali…" disabled={loading}/><button disabled={loading} onClick={()=>ask(q)}><Send size={18}/></button></div></>}
{tab==="more"&&<><div className="section"><small>MORE</small><h2>Made for family use</h2><p>Large controls, local-first playback, and a calm interface.</p></div><div className="info"><strong>🔊 Offline audio</strong><p>The 108× option uses the complete supplied 108-times recording at full length. The 11× recording list is intentionally empty for now and will be added later.</p></div><div className="info"><strong>🤖 Online AI</strong><p>Uses DeepSeek V4.1 Flash through NVIDIA AI and a secure Vercel serverless endpoint. Your API key stays on the server and is never sent to the browser.</p></div><div className="info"><strong>📱 Installable</strong><p>Use your browser's “Add to Home Screen” option to make it feel like an app.</p></div>}
</main><nav><button className={tab==="home"?"on":""} onClick={()=>setTab("home")}><Home size={20}/>Home</button><button className={tab==="week"?"on":""} onClick={()=>setTab("week")}><CalendarDays size={20}/>Week</button><button className={tab==="ask"?"on":""} onClick={()=>setTab("ask")}><Bot size={20}/>Ask</button><button className={tab==="more"?"on":""} onClick={()=>setTab("more")}><Settings size={20}/>More</button></nav></div>}

createRoot(document.getElementById("root")).render(<App/>);