import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import{motion}from"framer-motion";import{Bot,CalendarDays,Home,Info,Languages,Pause,Play,Send,Settings}from"lucide-react";import"./styles.css";
const D=[
["Sunday","रविवार","🌅","Surya · health, vision & success",[["Surya Mantra","ॐ घृणि सूर्याय नमः","Om Ghrini Suryaya Namaha","/audio/108x/surya-mantra.mp3"],["Surya Gayatri Mantra","ॐ भास्कराय विद्महे महातेजाय धीमहि तन्नो सूर्यः प्रचोदयात","Om Bhaskaraya Vidmahe Mahatejaya Dhimahi Tanno Suryah Prachodayat","/audio/108x/surya-gayatri.mp3"]]],
["Monday","सोमवार","🌙","Shiva · peace & letting go",[["Shiva Mantra","ॐ नमः शिवाय","Om Namah Shivaya","/audio/108x/shiva-mantra.mp3"],["Maha Mrityunjaya Mantra","ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥","Om Tryambakam Yajamahe","/audio/108x/maha-mrityunjaya.mp3"]]],
["Tuesday","मंगलवार","☄️","Hanuman & Ganesha · courage & obstacles",[["Hanuman Mantra","ॐ हनुमते नमः","Om Hanumate Namaha","/audio/108x/hanuman-mantra.mp3"],["Ganesha Mantra","ॐ गं गणपतये नमः","Om Gam Ganapataye Namaha","/audio/108x/ganesha.mp3"]]],
["Wednesday","बुधवार","🔱","Krishna & Vishnu · wisdom & devotion",[["Hare Krishna","हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे॥","Hare Krishna","/audio/108x/hare-krishna.mp3"],["Vishnu Mantra","ॐ नमो भगवते वासुदेवाय","Om Namo Bhagavate Vasudevaya","/audio/108x/vishnu-mantra.mp3"]]],
["Thursday","गुरुवार","🌾","Vishnu & Guru · learning & growth",[["Vishnu Dhyaan Mantra","ॐ नमो नारायणाय","Om Namo Narayanaya","/audio/108x/vishnu-dhyaan.mp3"],["Guru Mantra","ॐ गुरवे नमः","Om Gurave Namaha","/audio/108x/guru-mantra.mp3"]]],
["Friday","शुक्रवार","🌸","Lakshmi · abundance & grace",[["Lakshmi Mantra","ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै अस्माकम् दारिद्र्य नाशय प्रचुर धन देहि देहि क्लीं ह्रीं श्रीं ॐ","Om Shreem Hreem Kleem","/audio/108x/lakshmi-mantra.mp3"],["Mahalakshmi Mantra","ॐ श्री महालक्ष्म्यै नमः","Om Shri Mahalakshmyai Namaha","/audio/108x/mahalakshmi.mp3"]]],
["Saturday","शनिवार","⚖️","Shani · discipline & steadiness",[["Shani Mantra","ॐ शं शनैश्चराय नमः","Om Sham Shanaishcharaya Namaha","/audio/108x/shani.mp3"],["Shani Maha Mantra","ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः","Om Praam Preem Proum Sah","/audio/108x/shani-maha-mantra.mp3"]]]
];
const meaning="A traditional devotional mantra used for focused prayer, remembrance and a peaceful daily practice.";
function App(){const[t,setT]=useState(new Date().getDay()),[mi,setMi]=useState(0),[tab,setTab]=useState("home"),[play,setPlay]=useState(false),[audioError,setAudioError]=useState(""),[q,setQ]=useState(""),[msg,setMsg]=useState([]),[loading,setLoading]=useState(false),[lang,setLang]=useState("English"),audio=useRef(null),day=D[t],m=day[4][mi];
useEffect(()=>{if("serviceWorker"in navigator){navigator.serviceWorker.register("/sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{})}},[]);
useEffect(()=>{setMi(0)},[t]);useEffect(()=>{audio.current?.pause();if(audio.current){audio.current.currentTime=0;audio.current.load()}setPlay(false);setAudioError("")},[t,mi]);
const toggle=async()=>{if(!audio.current)return;if(play){audio.current.pause();setPlay(false)}else try{setAudioError("");if(audio.current.readyState<2)audio.current.load();await audio.current.play();setPlay(true)}catch(e){setPlay(false);setAudioError("Audio could not be loaded. Please refresh once after the latest update.")}};
const ask=async()=>{let x=q.trim();if(!x||loading)return;setMsg(v=>[...v,{r:"u",x}]);setQ("");setLoading(true);try{let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:x,mantra:{name:m[0],sanskrit:m[1],transliteration:m[2],meaning}})}),j=await r.json();if(!r.ok)throw 0;setMsg(v=>[...v,{r:"a",x:j.answer}])}catch{setMsg(v=>[...v,{r:"a",x:meaning}])}finally{setLoading(false)}};
return <div className="app"><header><div><div className="brand"><img src="/logo.svg" alt="MantraMitra logo"/><b>MantraMitra</b></div><small>Daily mantras · peaceful listening</small></div><button onClick={()=>setLang(lang==="English"?"हिन्दी":lang==="हिन्दी"?"বাংলা":"English")}><Languages size={19}/></button></header><main>
{tab==="home"&&<><section className="hero"><div><small>TODAY</small><h1>{day[2]} {day[0]} <em>{day[1]}</em></h1><p>{day[3]}</p></div><span>OFFLINE READY</span></section><section className={"player "+(play?"on":"")}><audio ref={audio} src={m[3]} preload="metadata" onCanPlay={()=>setAudioError("")} onError={()=>{setPlay(false);setAudioError("Audio file failed to load.")}} onEnded={()=>setPlay(false)}/><div className="orbarea"><div className="orb">ॐ</div>{[1,2,3].map(i=><motion.i key={i} animate={{scale:play?[1,1.2,1]:1,opacity:play?[.2,.45,.08]:.08}} transition={{duration:2,repeat:Infinity}}/>)}</div><div className="pill">{day[2]} {day[0]}</div><h2>{m[0]}</h2><div className="sanskrit">{m[1]}</div><div className="translit">{m[2]}</div><div className="audio-note">🎙️ Full-length 108× Sanskrit recording · offline ready</div>{audioError&&<div className="audio-note">⚠️ {audioError}</div>}<div className="controls"><button className="play" onClick={toggle}>{play?<Pause/>:<Play fill="currentColor"/>}{play?"Pause":"Play"}</button></div><div className="progress-count">108× full recording</div><div className="bars">{Array.from({length:20},(_,i)=><motion.span key={i} animate={{height:play?[8,10+(i%7)*5,8]:8}} transition={{repeat:Infinity,duration:.6}}/>)}</div><div className="meaning"><b><Info size={15}/> Simple meaning</b><p>{meaning}</p><button onClick={()=>setTab("ask")}>💬 Ask about this mantra</button></div></section><h3 className="sect">Today's mantras <button onClick={()=>setTab("week")}>View week</button></h3>{day[4].map((x,i)=><button className={"row "+(i===mi?"sel":"")} key={x[0]} onClick={()=>{setMi(i);setPlay(false)}}><strong>{"0"+(i+1)}</strong><div><b>{x[0]}</b><small>{x[2]}</small></div><Play size={17}/></button>)}</>}
{tab==="week"&&<><div className="section"><small>WEEKLY RHYTHM</small><h2>Choose a day</h2><p>All 108× recordings are full-length files for offline playback. The 11× collection is empty for now.</p></div><div className="days">{D.map((x,i)=><button className={i===t?"sel":""} key={x[0]} onClick={()=>{setT(i);setTab("home")}}><span>{x[2]}</span><b>{x[0]}</b><small>{x[1]}</small><em>{x[4].length} mantras</em></button>)}</div></>}
{tab==="ask"&&<><div className="section"><small>ONLINE GUIDE</small><h2>Ask about a mantra</h2><p>Online-only AI guide powered by DeepSeek V4.1 Flash through NVIDIA AI.</p></div><div className="suggests">{["What is the meaning?","Why chant this mantra?","How can I chant it?"].map(x=><button key={x} onClick={()=>{setQ(x);setTimeout(ask,0)}}>{x}</button>)}</div><div className="chat">{msg.length?msg.map((x,i)=><div key={i} className={"bubble "+x.r}>{x.x}</div>):<div className="empty"><Bot size={36}/><p>Ask about <b>{m[0]}</b>.</p></div>}{loading&&<div className="bubble a">Thinking…</div>}</div><div className="input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask in English, Hindi or Bengali…" disabled={loading}/><button disabled={loading} onClick={ask}><Send size={18}/></button></div></>}
{tab==="more"&&<><div className="section"><small>MORE</small><h2>Made for family use</h2><p>Large controls, local-first playback, and a calm interface.</p></div><div className="info"><strong>🔊 Offline audio</strong><p>108× uses the complete supplied recording. 11× remains intentionally empty until you upload those recordings.</p></div><div className="info"><strong>🤖 Online AI</strong><p>DeepSeek V4.1 Flash through a secure Vercel endpoint. The API key stays on the server.</p></div><div className="info"><strong>📱 Installable</strong><p>Use your browser's Add to Home Screen option.</p></div></>}
</main><nav><button className={tab==="home"?"on":""} onClick={()=>setTab("home")}><Home size={20}/>Home</button><button className={tab==="week"?"on":""} onClick={()=>setTab("week")}><CalendarDays size={20}/>Week</button><button className={tab==="ask"?"on":""} onClick={()=>setTab("ask")}><Bot size={20}/>Ask</button><button className={tab==="more"?"on":""} onClick={()=>setTab("more")}><Settings size={20}/>More</button></nav></div>}
createRoot(document.getElementById("root")).render(<App/>);